name: Package-Crates

on:
  release:
    types: [created]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Switch branch
      uses: actions/checkout@v4
    - name: Build crate
      run: cargo build --verbose
    - name: Test crate
      run: cargo test --verbose
    - name: Publish crate
      run: cargo publish --token ${{ secrets.CRATES_TOKEN }}
